### ISSUE TITLE
Add maven-compiler-plugin to pom file

### ISSUE THREAD

**Issue by michael-pont** [mathworks-ref-arch/matlab-aws-s3#1]
I tried running the mvn clean verify package command per the installation instructions.
Was receiving an error maven-compiler-plugin that needed source 7.
After googling the error, I figured that one could insert the following lines of code to explicitly set the maven compiler pluging version and source and target.

    <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
     <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
       </configuration>
    </plugin>
mvn clean verify package then worked.
For beginners/people not familiar with Java, is it possible to add this dependency into the Pom file?

**Comment by hosagrahara** [comment]
Thanks for the tip. We will incorporate this into the next release and use 1.7 to maintain compatibility to R2017a/b.

**Comment by hosagrahara** [comment]
This was fixed in v0.5.7. Please see 303dbf2b0acc7615f98a577d9877e16f227b2428. Closing out the issue.
