### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by zhs41** [mathworks-ref-arch/matlab-aws-s3#7]
It seems this does not work for large files. I tried using either putObject or save. It will give me JAVA exceptions with error code EntityTooLarge

**Comment by brownemi** [comment]
Hi zhs41,

Thanks for reporting this. Please expect an updated release in the next day or so that should address the issue.

**Comment by brownemi** [comment]
Release 0.6.1 of the package adds the requested support using the standard putObject, save etc. methods. For more detail or lower-level control see: https://github.com/mathworks-ref-arch/matlab-aws-s3/blob/master/Documentation/Multipart.md

**Comment by zhs41** [comment]
Thank you, will give it a try

**Comment by brownemi** [comment]
I'm assuming the solution in 0.6.1 worked and will close the issue.
